######################################################################
# Automatically generated by qmake (1.03a) Wed Nov 15 10:41:34 2006
######################################################################

TEMPLATE = app

# Input
HEADERS += gameborad.h nim.h
SOURCES += gameborad.cpp main.cpp nim.cpp
